#!/bin/bash
# yum install -y httpd
yum update -y
yum install ruby -y
yum install wget -y
cd /home/ec2-user
wget https://aws-codedeploy-eu-central-1.s3.amazonaws.com/latest/install
chmod +x ./install
sudo ./install auto -y

